return {
  CBHighlight= false, ScreenFilter= 1, TargetGoal= 93, TargetTrackerMode= 0, 
  ReceptorSize= 60, FullProgressBar= true, UserName= "", PasswordToken= "", 
  CustomizeGameplay= false, PlayerInfo= true, AvgScoreType= 0, GhostScoreType= 1, 
  OneShotMirror= false, BackgroundType= 1, LaneCoverHeight= 10, NPSGraph= false, 
  PracticeMode= false, CustomEvaluationWindowTimings= false, 
  leaderboardEnabled= false, DisplayPercent= true, ErrorBar= 1, 
  JudgeCounter= true, DisplayMean= false, 
  GameplayXYCoordinates= {
    ["7K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NPSGraphX= 0, NPSGraphY= 317, 
      NotefieldX= 0, NotefieldY= 0}, 
    ["8K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NPSGraphX= 0, NPSGraphY= 317, 
      NotefieldX= 0, NotefieldY= 0}, 
    ["9K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NPSGraphX= 0, NPSGraphY= 317, 
      NotefieldX= 0, NotefieldY= 0}, 
    ["10K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NPSGraphX= 0, NPSGraphY= 317, 
      NotefieldX= 0, NotefieldY= 0}, 
    ["12K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NPSGraphX= 0, NPSGraphY= 317, 
      NotefieldX= 0, NotefieldY= 0}, 
    ["16K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NPSGraphX= 0, NPSGraphY= 317, 
      NotefieldX= 0, NotefieldY= 0}, 
    ["3K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NPSGraphX= 0, NPSGraphY= 317, 
      NotefieldX= 0, NotefieldY= 0}, 
    ["4K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NPSGraphX= 0, NPSGraphY= 317, 
      NotefieldX= 0, NotefieldY= 0}, 
    ["5K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NPSGraphX= 0, NPSGraphY= 317, 
      NotefieldX= 0, NotefieldY= 0}, 
    ["6K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NPSGraphX= 0, NPSGraphY= 317, 
      NotefieldX= 0, NotefieldY= 0}}, JudgeType= 1, ErrorBarCount= 30, 
  GameplaySizes= {
    ["7K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, FullProgressBarHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, JudgeZoom= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, ComboZoom= 0.6, LifeP1Width= 1, 
      LeaderboardHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      NotefieldWidth= 1, LeaderboardWidth= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1}, 
    ["8K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, FullProgressBarHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, JudgeZoom= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, ComboZoom= 0.6, LifeP1Width= 1, 
      LeaderboardHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      NotefieldWidth= 1, LeaderboardWidth= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1}, 
    ["9K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, FullProgressBarHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, JudgeZoom= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, ComboZoom= 0.6, LifeP1Width= 1, 
      LeaderboardHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      NotefieldWidth= 1, LeaderboardWidth= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1}, 
    ["10K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, FullProgressBarHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, JudgeZoom= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, ComboZoom= 0.6, LifeP1Width= 1, 
      LeaderboardHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      NotefieldWidth= 1, LeaderboardWidth= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1}, 
    ["12K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, FullProgressBarHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, JudgeZoom= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, ComboZoom= 0.6, LifeP1Width= 1, 
      LeaderboardHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      NotefieldWidth= 1, LeaderboardWidth= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1}, 
    ["16K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, FullProgressBarHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, JudgeZoom= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, ComboZoom= 0.6, LifeP1Width= 1, 
      LeaderboardHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      NotefieldWidth= 1, LeaderboardWidth= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1}, 
    ["3K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, FullProgressBarHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, JudgeZoom= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, ComboZoom= 0.6, LifeP1Width= 1, 
      LeaderboardHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      NotefieldWidth= 1, LeaderboardWidth= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1}, 
    ["4K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, FullProgressBarHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, JudgeZoom= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, ComboZoom= 0.6, LifeP1Width= 1, 
      LeaderboardHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      NotefieldWidth= 1, LeaderboardWidth= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1}, 
    ["5K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, FullProgressBarHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, JudgeZoom= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, ComboZoom= 0.6, LifeP1Width= 1, 
      LeaderboardHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      NotefieldWidth= 1, LeaderboardWidth= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1}, 
    ["6K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, FullProgressBarHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, JudgeZoom= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, ComboZoom= 0.6, LifeP1Width= 1, 
      LeaderboardHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      NotefieldWidth= 1, LeaderboardWidth= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1}}, 
  NPSDisplay= true, MiniProgressBar= true, TargetTracker= true, 
  JudgmentText= true, LaneCover= 0, ComboText= true}