return {
  TargetGoal= 93, TargetTrackerMode= 0, CustomEvaluationWindowTimings= false, 
  leaderboardEnabled= false, ReceptorSize= 65, ErrorBarCount= 30, 
  UserName= "squoosh", 
  PasswordToken= "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5ldHRlcm5hb25saW5lLmNvbS9hcGkvY2xpZW50L2xvZ2luIiwiaWF0IjoxNzY1NDc5NjU1LCJleHAiOjM2NjI4MjM2NTUsIm5iZiI6MTc2NTQ3OTY1NSwianRpIjoick5ab2V4Njk3akRudFFNdiIsInN1YiI6IjEzMzMzIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImNsaWVudCI6Imp6QjM0eTJzVU1EeEFMZnpIWHhqS2txd3VvUWVhdGRkbkVVUG5md0JVb2lWaGVxWFNTOTREMzJGcUpBdmRTQmQ1RFF2UDNYNEJKQXVyU25IZXN6WDRTUWNEalFubnpIY3c2WEtjUE1LTDJrUk44V3NwSDl1Q0dxUlJWVllLazROanIiLCJ1c2VybmFtZSI6InNxdW9vc2gifQ.8ImghaEy2VYDQXejlbzQAR-hPvazoBrlhQ3metGcEvs", 
  CustomizeGameplay= false, 
  GameplayXYCoordinates= {
    ["3K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeY= 40, NPSGraphY= 317, NPSGraphX= 0, NotefieldY= 0, 
      ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NotefieldX= 0}, 
    ["4K"]= {ComboX= -123, ComboY= 159, ErrorBarX= 387, ErrorBarY= 280, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 384, FullProgressBarY= 443, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, DisplayPercentX= 295, 
      DisplayPercentY= 361, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeY= 175, NPSGraphY= 317, NPSGraphX= 0, 
      NotefieldY= -24, ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, 
      ReplayButtonsX= 809, ReplayButtonsY= 140, LifeP1X= 470, LifeP1Y= 264, 
      LifeP1Rotation= -90, PracticeCDGraphX= 10, PracticeCDGraphY= 85, 
      BPMTextX= 427, BPMTextY= 460, MusicRateX= 427, MusicRateY= 470, 
      NotefieldX= 0}, 
    ["5K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeY= 40, NPSGraphY= 317, NPSGraphX= 0, NotefieldY= 0, 
      ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NotefieldX= 0}, 
    ["6K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeY= 40, NPSGraphY= 317, NPSGraphX= 0, NotefieldY= 0, 
      ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NotefieldX= 0}, 
    ["7K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeY= 40, NPSGraphY= 317, NPSGraphX= 0, NotefieldY= 0, 
      ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NotefieldX= 0}, 
    ["8K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeY= 40, NPSGraphY= 317, NPSGraphX= 0, NotefieldY= 0, 
      ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NotefieldX= 0}, 
    ["9K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeY= 40, NPSGraphY= 317, NPSGraphX= 0, NotefieldY= 0, 
      ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NotefieldX= 0}, 
    ["10K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeY= 40, NPSGraphY= 317, NPSGraphX= 0, NotefieldY= 0, 
      ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NotefieldX= 0}, 
    ["12K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeY= 40, NPSGraphY= 317, NPSGraphX= 0, NotefieldY= 0, 
      ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NotefieldX= 0}, 
    ["16K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, DisplayPercentX= 257, 
      DisplayPercentY= 180, DisplayMeanX= 257, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeY= 40, NPSGraphY= 317, NPSGraphX= 0, NotefieldY= 0, 
      ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, NotefieldX= 0}}, AvgScoreType= 0, GhostScoreType= 1, 
  OneShotMirror= false, FullProgressBar= true, MiniProgressBar= true, 
  DisplayPercent= true, ErrorBar= 1, PracticeMode= false, PlayerInfo= true, 
  LaneCoverHeight= 10, NPSGraph= false, NPSDisplay= true, TargetTracker= true, 
  JudgmentText= true, JudgeType= 1, ComboText= true, JudgeCounter= true, 
  DisplayMean= false, CBHighlight= false, BackgroundType= 1, LaneCover= 0, 
  GameplaySizes= {
    ["3K"]= {ReplayButtonsSpacing= 0, LifeP1Width= 1, LifeP1Height= 1, 
      PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, MusicRateZoom= 1, 
      BPMTextZoom= 1, ComboZoom= 0.6, NotefieldWidth= 1, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      LeaderboardWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1}, 
    ["4K"]= {ReplayButtonsSpacing= 0, LifeP1Width= 1, LifeP1Height= 1, 
      PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, MusicRateZoom= 1, 
      BPMTextZoom= 1, ComboZoom= 0.46, NotefieldWidth= 1, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, JudgeZoom= 0.7, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1, NotefieldSpacing= -5, NotefieldHeight= 1, 
      LeaderboardWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1}, 
    ["5K"]= {ReplayButtonsSpacing= 0, LifeP1Width= 1, LifeP1Height= 1, 
      PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, MusicRateZoom= 1, 
      BPMTextZoom= 1, ComboZoom= 0.6, NotefieldWidth= 1, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      LeaderboardWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1}, 
    ["6K"]= {ReplayButtonsSpacing= 0, LifeP1Width= 1, LifeP1Height= 1, 
      PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, MusicRateZoom= 1, 
      BPMTextZoom= 1, ComboZoom= 0.6, NotefieldWidth= 1, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      LeaderboardWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1}, 
    ["7K"]= {ReplayButtonsSpacing= 0, LifeP1Width= 1, LifeP1Height= 1, 
      PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, MusicRateZoom= 1, 
      BPMTextZoom= 1, ComboZoom= 0.6, NotefieldWidth= 1, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      LeaderboardWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1}, 
    ["8K"]= {ReplayButtonsSpacing= 0, LifeP1Width= 1, LifeP1Height= 1, 
      PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, MusicRateZoom= 1, 
      BPMTextZoom= 1, ComboZoom= 0.6, NotefieldWidth= 1, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      LeaderboardWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1}, 
    ["9K"]= {ReplayButtonsSpacing= 0, LifeP1Width= 1, LifeP1Height= 1, 
      PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, MusicRateZoom= 1, 
      BPMTextZoom= 1, ComboZoom= 0.6, NotefieldWidth= 1, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      LeaderboardWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1}, 
    ["10K"]= {ReplayButtonsSpacing= 0, LifeP1Width= 1, LifeP1Height= 1, 
      PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, MusicRateZoom= 1, 
      BPMTextZoom= 1, ComboZoom= 0.6, NotefieldWidth= 1, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      LeaderboardWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1}, 
    ["12K"]= {ReplayButtonsSpacing= 0, LifeP1Width= 1, LifeP1Height= 1, 
      PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, MusicRateZoom= 1, 
      BPMTextZoom= 1, ComboZoom= 0.6, NotefieldWidth= 1, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      LeaderboardWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1}, 
    ["16K"]= {ReplayButtonsSpacing= 0, LifeP1Width= 1, LifeP1Height= 1, 
      PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, MusicRateZoom= 1, 
      BPMTextZoom= 1, ComboZoom= 0.6, NotefieldWidth= 1, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, 
      NPSGraphHeight= 1, NotefieldSpacing= 0, NotefieldHeight= 1, 
      LeaderboardWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1}}, 
  ScreenFilter= 1}