return {
  LaneCover= 0, TargetGoal= 93, LaneCoverHeight= 10, NPSGraph= false, 
  ErrorBarCount= 30, UserName= "", PasswordToken= "", CustomizeGameplay= false, 
  GameplayXYCoordinates= {
    ["3K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      NotefieldX= 0, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, JudgeY= 40, 
      DisplayPercentX= 257, DisplayPercentY= 180, DisplayMeanX= 257, 
      DisplayMeanY= 165, NPSDisplayX= 5, NPSDisplayY= 305, NPSGraphX= 0, 
      NPSGraphY= 317, ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, 
      ReplayButtonsX= 809, ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, 
      LifeP1Rotation= 0, PracticeCDGraphX= 10, PracticeCDGraphY= 85, 
      BPMTextX= 427, BPMTextY= 460, MusicRateX= 427, MusicRateY= 470, 
      NotefieldY= 0, MiniProgressBarY= 274}, 
    ["4K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      NotefieldX= 0, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, JudgeY= 40, 
      DisplayPercentX= 257, DisplayPercentY= 180, DisplayMeanX= 257, 
      DisplayMeanY= 165, NPSDisplayX= 5, NPSDisplayY= 305, NPSGraphX= 0, 
      NPSGraphY= 317, ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, 
      ReplayButtonsX= 809, ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, 
      LifeP1Rotation= 0, PracticeCDGraphX= 10, PracticeCDGraphY= 85, 
      BPMTextX= 427, BPMTextY= 460, MusicRateX= 427, MusicRateY= 470, 
      NotefieldY= 0, MiniProgressBarY= 274}, 
    ["5K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      NotefieldX= 0, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, JudgeY= 40, 
      DisplayPercentX= 257, DisplayPercentY= 180, DisplayMeanX= 257, 
      DisplayMeanY= 165, NPSDisplayX= 5, NPSDisplayY= 305, NPSGraphX= 0, 
      NPSGraphY= 317, ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, 
      ReplayButtonsX= 809, ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, 
      LifeP1Rotation= 0, PracticeCDGraphX= 10, PracticeCDGraphY= 85, 
      BPMTextX= 427, BPMTextY= 460, MusicRateX= 427, MusicRateY= 470, 
      NotefieldY= 0, MiniProgressBarY= 274}, 
    ["6K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      NotefieldX= 0, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, JudgeY= 40, 
      DisplayPercentX= 257, DisplayPercentY= 180, DisplayMeanX= 257, 
      DisplayMeanY= 165, NPSDisplayX= 5, NPSDisplayY= 305, NPSGraphX= 0, 
      NPSGraphY= 317, ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, 
      ReplayButtonsX= 809, ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, 
      LifeP1Rotation= 0, PracticeCDGraphX= 10, PracticeCDGraphY= 85, 
      BPMTextX= 427, BPMTextY= 460, MusicRateX= 427, MusicRateY= 470, 
      NotefieldY= 0, MiniProgressBarY= 274}, 
    ["7K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      NotefieldX= 0, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, JudgeY= 40, 
      DisplayPercentX= 257, DisplayPercentY= 180, DisplayMeanX= 257, 
      DisplayMeanY= 165, NPSDisplayX= 5, NPSDisplayY= 305, NPSGraphX= 0, 
      NPSGraphY= 317, ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, 
      ReplayButtonsX= 809, ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, 
      LifeP1Rotation= 0, PracticeCDGraphX= 10, PracticeCDGraphY= 85, 
      BPMTextX= 427, BPMTextY= 460, MusicRateX= 427, MusicRateY= 470, 
      NotefieldY= 0, MiniProgressBarY= 274}, 
    ["8K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      NotefieldX= 0, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, JudgeY= 40, 
      DisplayPercentX= 257, DisplayPercentY= 180, DisplayMeanX= 257, 
      DisplayMeanY= 165, NPSDisplayX= 5, NPSDisplayY= 305, NPSGraphX= 0, 
      NPSGraphY= 317, ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, 
      ReplayButtonsX= 809, ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, 
      LifeP1Rotation= 0, PracticeCDGraphX= 10, PracticeCDGraphY= 85, 
      BPMTextX= 427, BPMTextY= 460, MusicRateX= 427, MusicRateY= 470, 
      NotefieldY= 0, MiniProgressBarY= 274}, 
    ["9K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      NotefieldX= 0, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, JudgeY= 40, 
      DisplayPercentX= 257, DisplayPercentY= 180, DisplayMeanX= 257, 
      DisplayMeanY= 165, NPSDisplayX= 5, NPSDisplayY= 305, NPSGraphX= 0, 
      NPSGraphY= 317, ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, 
      ReplayButtonsX= 809, ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, 
      LifeP1Rotation= 0, PracticeCDGraphX= 10, PracticeCDGraphY= 85, 
      BPMTextX= 427, BPMTextY= 460, MusicRateX= 427, MusicRateY= 470, 
      NotefieldY= 0, MiniProgressBarY= 274}, 
    ["10K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      NotefieldX= 0, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, JudgeY= 40, 
      DisplayPercentX= 257, DisplayPercentY= 180, DisplayMeanX= 257, 
      DisplayMeanY= 165, NPSDisplayX= 5, NPSDisplayY= 305, NPSGraphX= 0, 
      NPSGraphY= 317, ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, 
      ReplayButtonsX= 809, ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, 
      LifeP1Rotation= 0, PracticeCDGraphX= 10, PracticeCDGraphY= 85, 
      BPMTextX= 427, BPMTextY= 460, MusicRateX= 427, MusicRateY= 470, 
      NotefieldY= 0, MiniProgressBarY= 274}, 
    ["12K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      NotefieldX= 0, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, JudgeY= 40, 
      DisplayPercentX= 257, DisplayPercentY= 180, DisplayMeanX= 257, 
      DisplayMeanY= 165, NPSDisplayX= 5, NPSDisplayY= 305, NPSGraphX= 0, 
      NPSGraphY= 317, ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, 
      ReplayButtonsX= 809, ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, 
      LifeP1Rotation= 0, PracticeCDGraphX= 10, PracticeCDGraphY= 85, 
      BPMTextX= 427, BPMTextY= 460, MusicRateX= 427, MusicRateY= 470, 
      NotefieldY= 0, MiniProgressBarY= 274}, 
    ["16K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      NotefieldX= 0, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, JudgeX= 0, JudgeY= 40, 
      DisplayPercentX= 257, DisplayPercentY= 180, DisplayMeanX= 257, 
      DisplayMeanY= 165, NPSDisplayX= 5, NPSDisplayY= 305, NPSGraphX= 0, 
      NPSGraphY= 317, ProgressBarPos= 1, LeaderboardX= 0, LeaderboardY= 48, 
      ReplayButtonsX= 809, ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, 
      LifeP1Rotation= 0, PracticeCDGraphX= 10, PracticeCDGraphY= 85, 
      BPMTextX= 427, BPMTextY= 460, MusicRateX= 427, MusicRateY= 470, 
      NotefieldY= 0, MiniProgressBarY= 274}}, 
  GameplaySizes= {
    ["3K"]= {BPMTextZoom= 1, JudgeZoom= 1, ComboZoom= 0.6, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, DisplayPercentZoom= 1, DisplayMeanZoom= 1, 
      NPSDisplayZoom= 0.4, NPSGraphWidth= 1, NPSGraphHeight= 1, LifeP1Height= 1, 
      PracticeCDGraphHeight= 1, PracticeCDGraphWidth= 0.8, LeaderboardWidth= 1, 
      LeaderboardHeight= 1, LeaderboardSpacing= 0, ReplayButtonsZoom= 1, 
      ReplayButtonsSpacing= 0, LifeP1Width= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, MusicRateZoom= 1}, 
    ["4K"]= {BPMTextZoom= 1, JudgeZoom= 1, ComboZoom= 0.6, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, DisplayPercentZoom= 1, DisplayMeanZoom= 1, 
      NPSDisplayZoom= 0.4, NPSGraphWidth= 1, NPSGraphHeight= 1, LifeP1Height= 1, 
      PracticeCDGraphHeight= 1, PracticeCDGraphWidth= 0.8, LeaderboardWidth= 1, 
      LeaderboardHeight= 1, LeaderboardSpacing= 0, ReplayButtonsZoom= 1, 
      ReplayButtonsSpacing= 0, LifeP1Width= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, MusicRateZoom= 1}, 
    ["5K"]= {BPMTextZoom= 1, JudgeZoom= 1, ComboZoom= 0.6, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, DisplayPercentZoom= 1, DisplayMeanZoom= 1, 
      NPSDisplayZoom= 0.4, NPSGraphWidth= 1, NPSGraphHeight= 1, LifeP1Height= 1, 
      PracticeCDGraphHeight= 1, PracticeCDGraphWidth= 0.8, LeaderboardWidth= 1, 
      LeaderboardHeight= 1, LeaderboardSpacing= 0, ReplayButtonsZoom= 1, 
      ReplayButtonsSpacing= 0, LifeP1Width= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, MusicRateZoom= 1}, 
    ["6K"]= {BPMTextZoom= 1, JudgeZoom= 1, ComboZoom= 0.6, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, DisplayPercentZoom= 1, DisplayMeanZoom= 1, 
      NPSDisplayZoom= 0.4, NPSGraphWidth= 1, NPSGraphHeight= 1, LifeP1Height= 1, 
      PracticeCDGraphHeight= 1, PracticeCDGraphWidth= 0.8, LeaderboardWidth= 1, 
      LeaderboardHeight= 1, LeaderboardSpacing= 0, ReplayButtonsZoom= 1, 
      ReplayButtonsSpacing= 0, LifeP1Width= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, MusicRateZoom= 1}, 
    ["7K"]= {BPMTextZoom= 1, JudgeZoom= 1, ComboZoom= 0.6, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, DisplayPercentZoom= 1, DisplayMeanZoom= 1, 
      NPSDisplayZoom= 0.4, NPSGraphWidth= 1, NPSGraphHeight= 1, LifeP1Height= 1, 
      PracticeCDGraphHeight= 1, PracticeCDGraphWidth= 0.8, LeaderboardWidth= 1, 
      LeaderboardHeight= 1, LeaderboardSpacing= 0, ReplayButtonsZoom= 1, 
      ReplayButtonsSpacing= 0, LifeP1Width= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, MusicRateZoom= 1}, 
    ["8K"]= {BPMTextZoom= 1, JudgeZoom= 1, ComboZoom= 0.6, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, DisplayPercentZoom= 1, DisplayMeanZoom= 1, 
      NPSDisplayZoom= 0.4, NPSGraphWidth= 1, NPSGraphHeight= 1, LifeP1Height= 1, 
      PracticeCDGraphHeight= 1, PracticeCDGraphWidth= 0.8, LeaderboardWidth= 1, 
      LeaderboardHeight= 1, LeaderboardSpacing= 0, ReplayButtonsZoom= 1, 
      ReplayButtonsSpacing= 0, LifeP1Width= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, MusicRateZoom= 1}, 
    ["9K"]= {BPMTextZoom= 1, JudgeZoom= 1, ComboZoom= 0.6, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, DisplayPercentZoom= 1, DisplayMeanZoom= 1, 
      NPSDisplayZoom= 0.4, NPSGraphWidth= 1, NPSGraphHeight= 1, LifeP1Height= 1, 
      PracticeCDGraphHeight= 1, PracticeCDGraphWidth= 0.8, LeaderboardWidth= 1, 
      LeaderboardHeight= 1, LeaderboardSpacing= 0, ReplayButtonsZoom= 1, 
      ReplayButtonsSpacing= 0, LifeP1Width= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, MusicRateZoom= 1}, 
    ["10K"]= {BPMTextZoom= 1, JudgeZoom= 1, ComboZoom= 0.6, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, DisplayPercentZoom= 1, DisplayMeanZoom= 1, 
      NPSDisplayZoom= 0.4, NPSGraphWidth= 1, NPSGraphHeight= 1, LifeP1Height= 1, 
      PracticeCDGraphHeight= 1, PracticeCDGraphWidth= 0.8, LeaderboardWidth= 1, 
      LeaderboardHeight= 1, LeaderboardSpacing= 0, ReplayButtonsZoom= 1, 
      ReplayButtonsSpacing= 0, LifeP1Width= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, MusicRateZoom= 1}, 
    ["12K"]= {BPMTextZoom= 1, JudgeZoom= 1, ComboZoom= 0.6, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, DisplayPercentZoom= 1, DisplayMeanZoom= 1, 
      NPSDisplayZoom= 0.4, NPSGraphWidth= 1, NPSGraphHeight= 1, LifeP1Height= 1, 
      PracticeCDGraphHeight= 1, PracticeCDGraphWidth= 0.8, LeaderboardWidth= 1, 
      LeaderboardHeight= 1, LeaderboardSpacing= 0, ReplayButtonsZoom= 1, 
      ReplayButtonsSpacing= 0, LifeP1Width= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, MusicRateZoom= 1}, 
    ["16K"]= {BPMTextZoom= 1, JudgeZoom= 1, ComboZoom= 0.6, ErrorBarWidth= 240, 
      ErrorBarHeight= 10, TargetTrackerZoom= 0.4, FullProgressBarWidth= 1, 
      FullProgressBarHeight= 1, DisplayPercentZoom= 1, DisplayMeanZoom= 1, 
      NPSDisplayZoom= 0.4, NPSGraphWidth= 1, NPSGraphHeight= 1, LifeP1Height= 1, 
      PracticeCDGraphHeight= 1, PracticeCDGraphWidth= 0.8, LeaderboardWidth= 1, 
      LeaderboardHeight= 1, LeaderboardSpacing= 0, ReplayButtonsZoom= 1, 
      ReplayButtonsSpacing= 0, LifeP1Width= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, MusicRateZoom= 1}}, 
  JudgeType= 1, AvgScoreType= 0, GhostScoreType= 1, OneShotMirror= false, 
  BackgroundType= 1, DisplayPercent= true, ErrorBar= 1, JudgeCounter= true, 
  DisplayMean= false, CustomEvaluationWindowTimings= false, TargetTracker= true, 
  NPSDisplay= true, leaderboardEnabled= false, PracticeMode= false, 
  JudgmentText= true, FullProgressBar= true, ComboText= true, PlayerInfo= true, 
  MiniProgressBar= true, CBHighlight= false, ScreenFilter= 1, 
  TargetTrackerMode= 0, ReceptorSize= 60}