return {
  CBHighlight= false, ScreenFilter= 1, TargetGoal= 93, TargetTrackerMode= 0, 
  ReceptorSize= 60, ErrorBarCount= 30, UserName= "squoosh", 
  PasswordToken= "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5ldHRlcm5hb25saW5lLmNvbS9hcGkvY2xpZW50L2xvZ2luIiwiaWF0IjoxNzY4MzcyNjE2LCJleHAiOjM2NjU3MTY2MTYsIm5iZiI6MTc2ODM3MjYxNiwianRpIjoiMDdiSlY1WExVTW8yeGJVVSIsInN1YiI6IjEzMzMzIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImNsaWVudCI6Imp6QjM0eTJzVU1EeEFMZnpIWHhqS2txd3VvUWVhdGRkbkVVUG5md0JVb2lWaGVxWFNTOTREMzJGcUpBdmRTQmQ1RFF2UDNYNEJKQXVyU25IZXN6WDRTUWNEalFubnpIY3c2WEtjUE1LTDJrUk44V3NwSDl1Q0dxUlJWVllLazROanIiLCJ1c2VybmFtZSI6InNxdW9vc2gifQ.3kK2uOXHC_jbB0Ky7k9x_WNM4Xjv74gqdFnVrhaAM1g", 
  CustomizeGameplay= false, PlayerInfo= true, AvgScoreType= 0, GhostScoreType= 1, 
  OneShotMirror= false, BackgroundType= 1, LaneCoverHeight= 10, NPSGraph= false, 
  PracticeMode= false, CustomEvaluationWindowTimings= false, 
  leaderboardEnabled= false, DisplayPercent= true, ErrorBar= 1, 
  JudgeCounter= true, DisplayMean= false, MiniProgressBar= true, 
  FullProgressBar= true, 
  GameplaySizes= {
    ["7K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, LifeP1Width= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, NPSGraphHeight= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, FullProgressBarHeight= 1, 
      LeaderboardWidth= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, ComboZoom= 0.6}, 
    ["8K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, LifeP1Width= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, NPSGraphHeight= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, FullProgressBarHeight= 1, 
      LeaderboardWidth= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, ComboZoom= 0.6}, 
    ["9K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, LifeP1Width= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, NPSGraphHeight= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, FullProgressBarHeight= 1, 
      LeaderboardWidth= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, ComboZoom= 0.6}, 
    ["10K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, LifeP1Width= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, NPSGraphHeight= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, FullProgressBarHeight= 1, 
      LeaderboardWidth= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, ComboZoom= 0.6}, 
    ["12K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, LifeP1Width= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, NPSGraphHeight= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, FullProgressBarHeight= 1, 
      LeaderboardWidth= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, ComboZoom= 0.6}, 
    ["16K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, LifeP1Width= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, NPSGraphHeight= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, FullProgressBarHeight= 1, 
      LeaderboardWidth= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, ComboZoom= 0.6}, 
    ["3K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, LifeP1Width= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, NPSGraphHeight= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, FullProgressBarHeight= 1, 
      LeaderboardWidth= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, ComboZoom= 0.6}, 
    ["4K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, LifeP1Width= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, NPSGraphHeight= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, FullProgressBarHeight= 1, 
      LeaderboardWidth= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, ComboZoom= 0.6}, 
    ["5K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, LifeP1Width= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, NPSGraphHeight= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, FullProgressBarHeight= 1, 
      LeaderboardWidth= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, ComboZoom= 0.6}, 
    ["6K"]= {ErrorBarWidth= 240, ErrorBarHeight= 10, TargetTrackerZoom= 0.4, 
      FullProgressBarWidth= 1, LeaderboardHeight= 1, LeaderboardSpacing= 0, 
      ReplayButtonsZoom= 1, ReplayButtonsSpacing= 0, LifeP1Width= 1, 
      LifeP1Height= 1, PracticeCDGraphWidth= 0.8, PracticeCDGraphHeight= 1, 
      MusicRateZoom= 1, BPMTextZoom= 1, NPSGraphHeight= 1, NotefieldWidth= 1, 
      NotefieldSpacing= 0, NotefieldHeight= 1, FullProgressBarHeight= 1, 
      LeaderboardWidth= 1, JudgeZoom= 1, DisplayPercentZoom= 1, 
      DisplayMeanZoom= 1, NPSDisplayZoom= 0.4, NPSGraphWidth= 1, ComboZoom= 0.6}}, 
  GameplayXYCoordinates= {
    ["7K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      NotefieldX= 0, NotefieldY= 0, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, DisplayMeanX= 257, DisplayPercentY= 180, 
      NPSGraphX= 0, NPSGraphY= 317}, 
    ["8K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      NotefieldX= 0, NotefieldY= 0, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, DisplayMeanX= 257, DisplayPercentY= 180, 
      NPSGraphX= 0, NPSGraphY= 317}, 
    ["9K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      NotefieldX= 0, NotefieldY= 0, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, DisplayMeanX= 257, DisplayPercentY= 180, 
      NPSGraphX= 0, NPSGraphY= 317}, 
    ["10K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      NotefieldX= 0, NotefieldY= 0, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, DisplayMeanX= 257, DisplayPercentY= 180, 
      NPSGraphX= 0, NPSGraphY= 317}, 
    ["12K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      NotefieldX= 0, NotefieldY= 0, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, DisplayMeanX= 257, DisplayPercentY= 180, 
      NPSGraphX= 0, NPSGraphY= 317}, 
    ["16K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      NotefieldX= 0, NotefieldY= 0, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, DisplayMeanX= 257, DisplayPercentY= 180, 
      NPSGraphX= 0, NPSGraphY= 317}, 
    ["3K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      NotefieldX= 0, NotefieldY= 0, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, DisplayMeanX= 257, DisplayPercentY= 180, 
      NPSGraphX= 0, NPSGraphY= 317}, 
    ["4K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      NotefieldX= 0, NotefieldY= 0, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, DisplayMeanX= 257, DisplayPercentY= 180, 
      NPSGraphX= 0, NPSGraphY= 317}, 
    ["5K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      NotefieldX= 0, NotefieldY= 0, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, DisplayMeanX= 257, DisplayPercentY= 180, 
      NPSGraphX= 0, NPSGraphY= 317}, 
    ["6K"]= {ComboX= 30, ComboY= -20, ErrorBarX= 427, ErrorBarY= 293, 
      TargetTrackerX= 453, TargetTrackerY= 270, MiniProgressBarX= 471, 
      MiniProgressBarY= 274, FullProgressBarX= 427, FullProgressBarY= 20, 
      JudgeCounterX= 227, JudgeCounterY= 240, DisplayPercentX= 257, 
      NotefieldX= 0, NotefieldY= 0, DisplayMeanY= 165, NPSDisplayX= 5, 
      NPSDisplayY= 305, JudgeX= 0, JudgeY= 40, ProgressBarPos= 1, 
      LeaderboardX= 0, LeaderboardY= 48, ReplayButtonsX= 809, 
      ReplayButtonsY= 140, LifeP1X= 178, LifeP1Y= 10, LifeP1Rotation= 0, 
      PracticeCDGraphX= 10, PracticeCDGraphY= 85, BPMTextX= 427, BPMTextY= 460, 
      MusicRateX= 427, MusicRateY= 470, DisplayMeanX= 257, DisplayPercentY= 180, 
      NPSGraphX= 0, NPSGraphY= 317}}, NPSDisplay= true, JudgeType= 1, TargetTracker= true, 
  JudgmentText= true, LaneCover= 0, ComboText= true}